[[redirects]]
  from = "/wiki/*"
  to = "https://cs.wikipedia.org/wiki/:splat"
  force = true
  [redirects.headers]
    X-From = "Netlify"


[[redirects]]
  from = "/bestWeekWikiArticle"
  to = "https://cs.wikipedia.org/wiki/Wikipedie:%C4%8Cl%C3%A1nek_t%C3%BDdne"
  force = true
  headers = {X-From = "Netlify"}